Combat Rework v1 (untested)
crpg2/crpg pull request #377
Opened 2024-08-24 00:42 UTC by Yeldur

2024-12-22 12:46 UTC, namidaka requested changes

2024-12-22 12:46 UTC, namidaka commented on src/Module.Server/Common/Models/CrpgStrikeMagnitudeModel.cs
>      }
Seems very wrong , you're changing swing spot

2024-12-22 12:46 UTC, namidaka commented on src/Module.Server/ModuleData/managed_core_parameters.xml
Same here dangerous change , needs testing. This is a sweetspot change

2024-12-22 12:46 UTC, namidaka commented on src/Module.Server/ModuleData/native_parameters.xml
> -    <native_parameter id="defend_speed_multiplier" value="20.2"/> <!-- Native = 3.2 -->
Why change DefendSpeedMultiplier?

2024-12-22 12:46 UTC, namidaka commented on src/Module.Server/ModuleData/native_parameters.xml
> -    <native_parameter id="running_sides_speed_multiplier" value="0.725" />   <!-- Native = 0.65-->
Looks like you just went in and reverted blindly.
What you're looking to revert is actually those three
  <native_parameter id="ready_speed_multiplier" value="0.88"/>  <!-- Native = 2.2 -->
    <native_parameter id="running_backward_speed_multiplier" value="0.6" />  <!-- Native = 0.5 -->
    <native_parameter id="running_sides_speed_multiplier" value="0.725" />  
    
    The rest should not be touched

2025-01-04 23:06 UTC, Yeldur commented
Closing this for now as this will be largely out of date and will be rendered null & void by changes made during MVP Test.

2025-01-04 23:06 UTC, closed without merging